code_style:
  default: [codespell,drupal,drupalpractice]
  rules:
    media: ignore
    scripts: ignore
deploy:
  master:
    server: "karma.vps-private.net"
    user: "d6"
    type:
      name: "custom"
      settings:
        domain: "d6.drupalru.drupal-site.net"
        account-name: "root"
        account-mail: "gor.martsen@gmail.com"
        account-pass: "d6testing"
        site-name: "Drupal.ru dev site"
        site-mail: "noreply@d6.drupalru.drupal-site.net"
        database-user: "d6_dev"
        database-name: "d6_dev"
        database-pass: "dev678yh"
        devel: TRUE
    dir: '{home}/github'
    init: '{deploy_dir}/scripts/init.sh'
    before: '{deploy_dir}/scripts/before.sh'
    after: '{deploy_dir}/scripts/after.sh'
