code_style:
  default: [codespell,drupal,drupalpractice]
  rules:
    media: ignore
    scripts: ignore
    data: ignore
    README.md: ignore
    modules/validate_api/antiswearing_validate/obscene: ignore
deploy:
  master:
    server: "karma.vps-private.net"
    user: "drupal"
    type:
      name: "custom"
      settings:
        domain: "production.drupal.ru"
        account-name: "root"
        account-mail: "gor.martsen@gmail.com"
        account-pass: "d6testing"
        site-name: "Drupal.ru dev site"
        site-mail: "noreply@production.drupal.ru"
        database-user: "drupal_prod"
        database-name: "drupal_production"
        database-pass: "Jrbn43t45t"
        devel: TRUE
    dir: '{home}/github/{branch}'
    init: '{deploy_dir}/scripts/init.sh'
    before: '{deploy_dir}/scripts/before.sh'
    after: '{deploy_dir}/scripts/after.sh'
  stage:
    server: "karma.vps-private.net"
    user: "stage"
    type:
      name: "custom"
      settings:
        domain: "stage.drupal.ru"
        account-name: "root"
        account-mail: "gor.martsen@gmail.com"
        account-pass: "d6testing"
        site-name: "Drupal.ru dev site"
        site-mail: "noreply@production.drupal.ru"
        database-user: "stage_main"
        database-name: "stage_main"
        database-pass: "BHjrb454"
        devel: TRUE
    dir: '{home}/github/{branch}'
    init: '{deploy_dir}/scripts/init.sh'
    before: '{deploy_dir}/scripts/before.sh'
    after: '{deploy_dir}/scripts/after.sh'
  pull_request:
    robin:
      domain: "{pr_number}.pr.drupal.ru"
      server: "karma.vps-private.net"
      user: "pr"
      password: "NJRk4355d"
    type:
      name: "custom"
      settings:
        domain: "{domainname}"
        account-name: "devel"
        account-mail: "devel@drupal.ru"
        account-pass: "drupalrutesting"
        site-name: "PR {pr_number}"
        site-mail: "noreply@{domainname}"
    dir: '{home}/github/pr/{pr_number}'
    init: '{deploy_dir}/scripts/init.sh'
    before: '{deploy_dir}/scripts/before.sh'
    after: '{deploy_dir}/scripts/after.sh'

