deploy:
  dev:
    server: drupal.ru
    username: drupal
    dir: '{home}/github/repository'
    env_vars:
      environment: dev
      store_versions: 13
      profile: drupalru
    scripts:
      after: '{deploy_dir}/scripts/zen.ci/deploy.sh'
  stage:
    server: drupal.ru
    username: drupal
    dir: '{home}/github/repository'
    env_vars:
      environment: stage
      store_versions: 13
      profile: drupalru
    scripts:
      after: '{deploy_dir}/scripts/zen.ci/deploy.sh'